### ISSUE TITLE
R7RSHomePage updates

### ISSUE THREAD

**Issue by lassik** [johnwcowan/r7rs-work#2]
@johnwcowan, can you check that the URLs on `R7RSHomePage.md` are up to date? Some of them still point to BitBucket.

That document should probably also link to the repo's top-level `https://github.com/johnwcowan/r7rs-work` URL for people who want to browse the pre-SRFIs.

Linking to the nice PDF someone made of the Red Edition a few months back would also be great.

We should really establish that `files.scheme.org` so we can get easier permanent URLs for our PDFs.

cc @filiplajszczak via https://github.com/schemedoc/awesome-scheme/pull/60

**Comment by johnwcowan** [comment]
Bitbucket links all fixed; top-level link added; I don't know where the Red Edition PDF is currently hosted.

I'll try to get back to the S3 bucket for the files.

**Comment by arthurgleckler** [comment]
On Fri, Aug 14, 2020 at 8:24 PM John Cowan <notifications@github.com> wrote:

> Bitbucket links all fixed; top-level link added; I don't know where the
> Red Edition PDF is currently hosted.
>
> Here's the link I have for the Red Edition PDF:

https://gitlab.com/vmanis/r7rs-large/-/blob/master/reports/red.pdf

**Comment by lassik** [comment]
> Bitbucket links all fixed; top-level link added; I don't know where the Red Edition PDF is currently hosted.

Thanks! I'll search my email for the PDF link.

> I'll try to get back to the S3 bucket for the files.

If you haven't done it yet, may I suggest we go with a traditional Linux server? The Scheme community has many people (most especially the GNU people) who are suspicious of tech giants like Amazon. A standard Linux server with nginx will be very easy to arrange; I already know of three that are in active Schemers' hands.

**Comment by lassik** [comment]
> I'll search my email for the PDF link.

Arthur beat me to it.

**Comment by johnwcowan** [comment]
Link added.

As for files.schemers.org, if I am going to do it, I'm going to decide how much I'm willing to pay for it.  In addition, I am suspicious of *not* using tech giants: people easily forget about their private servers, or they get taken down for one reason or another, and the community loses parts of its history (that happened to much of the R6RS infrastructure).  I particularly favor Amazon because there I am not just a user, I am a paying customer.

The current issues are, I think, just config issues: when I get the bucket fully public and populated it with a few files, I think everything else will be easy-peasy.

**Comment by johnwcowan** [comment]
Okay, the S3 bucket is working: [README.md](http://s3.amazonaws.com/org.schemers.files/README.md) is the temporary file.

The domain files.schemers.org should be made to point to "http://s3.amazonaws.com/org.schemers.files", and then [this link](http://files.schemers.org/README.md) should also work.

As I mentioned, the index file will have to be maintained by hand.

You can now start sending me files to host, either by email or by URL.
